# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2f2b727486f315fd998e4d923830f621589f55d6eec9892f27eee7da8eff3f73e8b648a5fe2ca3ecd57f9252138b7d0405233087b87dca17756892a8d576f84d

test:
  secret_key_base: 0c5003c458902dec2b19a0ed91a4e69e6e8bffa0c35d01e25c1ac57a6ee54590b80d00cd90ca7617a354aac0d91ce95e304e68a480dc68e008ee4fcc51420946

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
