# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 76bfdcf838fc22aeac10c261a7a631b09b9a0a7b04cf68ac1c57faae1ded4d57d4a0bc2b6a6490014445b04db83abdec778f9c92c0e9235dd8bbf0a922a554ef

test:
  secret_key_base: 357ef4caa3364c15566a8ae7be3166ae02ccd7d95c02ce7c97609cb0574614a382a706b4f6e628f435d7f8809b1b7c4a8280611e17c152bc71ee36f0074f9e84

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
